### ISSUE TITLE
connection GPIO 4 Raspi

### ISSUE THREAD

**Issue by felipeguerrero87** [thisdavej/ds18b20-raspi#8]
only serves in GPIO 4?

**Comment by thisdavej** [comment]
According to [this answer](https://www.raspberrypi.org/forums/viewtopic.php?t=65137#p510744), you can add an entry to `/boot/cmdline.txt` to specify a different GPIO pin other than pin 4 for the 1-wire interface (used by the DS18B20) as follows:

`bcm2708.w1_gpio_pin=8`

My npm package will continue to function since it reads from the sysfs file system used by the 1-wire interface and the same files will exist whether the default GPIO pin 4 is used or this technique is used to change the default 1-wire GPIO pin.
